{
  "type": "record",
  "name": "CepRequest",
  "fields": [
    {"name": "cep", "type": "string"},
    {"name": "requestId", "type": "string"}
  ]
}

{
  "type": "record",
  "name": "CepResponse",
  "fields": [
    {"name": "cep", "type": "string"},
    {"name": "logradouro", "type": "string"},
    {"name": "complemento", "type": "string"},
    {"name": "bairro", "type": "string"},
    {"name": "localidade", "type": "string"},
    {"name": "uf", "type": "string"},
    {"name": "ibge", "type": "string"},
    {"name": "gia", "type": "string"},
    {"name": "ddd", "type": "string"},
    {"name": "siafi", "type": "string"},
    {"name": "erro", "type": "boolean"},
    {"name": "requestId", "type": "string"}
  ]
}
